[package]
name="sakura-launcher"
version="0.9.0"
edition="2021"

[build-dependencies]
tauri-build={version="2"}

[dependencies]
tauri={version="2",features=[]}
serde={version="1",features=["derive"]}
serde_json={version="1"}
reqwest={version="0.12",default-features=false,features=["blocking","json","rustls-tls"]}
zip={version="2",features=["deflate"]}
urlencoding="2"

[features]
default=["custom-protocol"]
custom-protocol=["tauri/custom-protocol"]
